---
- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - nodejs
    - build-essential
  tags:
    - nodejs


- name: Install Packages | npm
  npm:
    state: latest
    name: "{{ item }}"
    global: yes
  with_items: "{{ node_packages }}"
  when: node_packages is iterable
  tags:
    - nodejs
